name: github_search
description: GitHub APIを利用してGitHubのリポジトリを検索するアプリ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_riverpod: ^2.1.1
  flutter_state_notifier: ^0.7.1
  flutter_svg: ^1.1.6
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.1.0
  gap: ^2.0.1
  go_router: ^6.0.0
  hexcolor: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  import_sorter: ^4.6.0
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.6.0
  lottie: ^2.1.0
  markdown: ^6.0.1
  number_display: ^3.0.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  responsive_framework: ^0.2.0
  roggle: ^0.3.0
  shimmer: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.7
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner: ^2.2.1
  fast_i18n: ^5.12.6
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.15
  golden_toolkit: ^0.14.0
  import_path_converter: ^1.0.0
  isar_generator: ^3.0.5
  json_serializable: ^6.3.2
  mocktail: ^0.3.0
  path: ^1.8.2
  pedantic_mono: ^1.20.1
  sqflite_common_ffi: ^2.2.0+1

flutter:
  # assets:
  # - assets/images/
  # - assets/lottie/
  uses-material-design: true

flutter_gen:
  output: lib/util/assets/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: 'ic_launcher'
  ios: true
  macos: true
  windows: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#eeeeee'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: '#eeeeee'
  image: 'assets/images/splash.png'
  color_dark: '#262626'
  image_dark: 'assets/images/splash_dark.png'

  # Android12以上はAndroidOS側でアプリアイコンをスプラッシュ表示してしまうので以下の通り設定が必要
  android_12:
    image: 'assets/images/splash_android_12.png'
    icon_background_color: '#eeeeee'
    image_dark: 'assets/images/splash_android_12_dark.png'
    icon_background_color_dark: '#262626'
